logging:
  level:
    root: INFO
    br.eti.archanjo: INFO
    org.springframework: INFO
    br.eti.archanjo.webcron.quartz: INFO
spring:
  profiles:
    active: default
  application:
    name: webcron-service
  redis:
    database: 15
    host: vm.services
    port: 6379
  datasource:
    url: jdbc:mysql://vm.services:3306/webcrons?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: q1w2e3
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: vm.services
      database: webcron
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  tomcat:
    remote-ip-header: X-Forwarded-For

webcron:
  httplimits:
    limit: 100
    page: 0
  logging:
    folder: /home/fabricio/1/log
  shell:
    bin: /bin/bash
  system-user-file: /etc/passwd
